### Create a new route (and ensure that the route distance does not fluctuate)
POST http://localhost:8000/routes
Accept: application/json
Content-Type: application/json
Authorization: r86gmvwr0qoyjvl4spw9xtxo5civ629k

{
  "start_address": "Soborna 1",
  "end_address": "Soborna 10"
}

> {%
    client.assert(response.status == 200)
    client.assert(JSON.stringify(response.body) == JSON.stringify({
        "id": 2,
        "start_address": "Soborna 1",
        "end_address": "Soborna 10",
        "distance_kilometers": 0.301,
        "mean_time_minutes": 0.3612
    }))
%}

### Refresh the route (and ensure that the route distance & time does not fluctuate)
POST http://localhost:8000/routes/2/refresh
Accept: application/json
Content-Type: application/json
Authorization: r86gmvwr0qoyjvl4spw9xtxo5civ629k

{}

> {%
    client.assert(response.status == 200)
    client.assert(JSON.stringify(response.body) == JSON.stringify({
        "id": 2,
        "start_address": "Soborna 1",
        "end_address": "Soborna 10",
        "distance_kilometers": 0.301,
        "mean_time_minutes": 0.3612
    }))
%}

### Validate the authentication for the route refreshing
POST http://localhost:8000/routes/2/refresh
Accept: application/json
Content-Type: application/json
Authorization:

> {%
    client.assert(response.status == 401)
    client.assert(JSON.stringify(response.body) == JSON.stringify({
        "type": "unauthorized",
        "message": "The token '' is not owned by any user"
    }))
%}

### Refresh unexisting route
POST http://localhost:8000/routes/-1/refresh
Accept: application/json
Content-Type: application/json
Authorization: r86gmvwr0qoyjvl4spw9xtxo5civ629k

{}

> {%
    client.assert(response.status == 404)
    client.assert(JSON.stringify(response.body) == JSON.stringify({
        type: "route_not_found",
        message: "The <Route id=-1> was not found"
    }))
%}

### Read the existing route
GET http://localhost:8000/routes/2
Accept: application/json
Content-Type: application/json
Authorization: r86gmvwr0qoyjvl4spw9xtxo5civ629k

{}

> {%
    client.assert(response.status == 200)
    client.assert(JSON.stringify(response.body) == JSON.stringify({
        "id": 2,
        "start_address": "Soborna 1",
        "end_address": "Soborna 10",
        "distance_kilometers": 0.301,
        "mean_time_minutes": 0.3612
    }))
%}

### Read unexisting route
GET http://localhost:8000/routes/-1
Accept: application/json
Content-Type: application/json
Authorization: r86gmvwr0qoyjvl4spw9xtxo5civ629k

{}

> {%
    client.assert(response.status == 404)
    client.assert(JSON.stringify(response.body) == JSON.stringify({
        type: "route_not_found",
        message: "The <Route id=-1> was not found"
    }))
%}

### Validate that routes are accessible only for authorized users
GET http://localhost:8000/routes/2
Accept: application/json
Content-Type: application/json
Authorization:

> {%
    client.assert(response.status == 401)
    client.assert(JSON.stringify(response.body) == JSON.stringify({
        "type": "unauthorized",
        "message": "The token '' is not owned by any user"
    }))
%}